baseurl         = ""
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "ANNA CAMACHO"
  subtitle    = "Playing with Lines"

  cover       = "img/blog-cover.jpg"
  description = "Anna's personal Blog"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = ["built/site.css"]
  RSSLink = ""

  twitterName = "MinaCamachov"
  githubName = "Minacava"

  logo = "cover-img/ANNA.png"
  orgName = "AC"
  orgWebsite = ""
  orgDescription = ""

  author = "Anna Camacho"
  authorAvatar = "cover-img/anna.jpg"
  authorLocation = "Barcelona, Spain"
  authorWebsite = "www.bouncingshield.com"
  authorDescription = "Reader and Writer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "New Posts"
  url = "/tags/NewPosts/"
  weight = 100

[[menu.main]]
  name = "Books"
  url = "/categories/Books/"
  weight = 99

[[menu.main]]
  name = "Created with Love By #MinaCamachov"
  url = "https://bouncingshield.com/"
  weight = 95
